import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Bài viết",
  description: "Generated by tuan anh",
};

export default function Baiviet({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}
