import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Phiếu quà tặng",
  description: "Generated by tuan anh",
};

export default function PhieuQuaTang({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
